### ISSUE TITLE
DOES THIS WORK NOW?

### ISSUE THREAD

**Issue by M-0-N-K** [bewisse/modheader_selenium#6]
I was using this till yesterday and it worked fine. But not anymore? 
is there something I am doing wrong?
[
![Screenshot from 2019-11-17 16-32-25](https://user-images.githubusercontent.com/52029128/69006679-5f5e2980-0958-11ea-95b3-5f0e5c8c918e.png)
](url)

**Comment by hao1300** [comment]
Yes, it should still work. Please make sure the extension is properly installed in your webdriver.
